spring.application.name=clucknet-backend
server.port=8080

# ================= DATABASE =================
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

influx.url=${INFLUX_URL}
influx.token=${INFLUX_TOKEN}
influx.org=${INFLUX_ORG}
influx.bucket=${INFLUX_BUCKET}

# ================= MQTT HIVEMQ =================
mqtt.broker-url=${MQTT_BROKER_URL}
mqtt.username=${MQTT_USER}
mqtt.password=${MQTT_PASSWORD}
mqtt.client-id=${MQTT_CLIENT_ID}
mqtt.topic=${MQTT_TOPIC}